'use strict';

const USER_ROLE_ADMIN = 'ADMIN';
const USER_ROLE_USER = 'USER';

const PROFILE_TYPE_PRIVATE = 'PRIVATE';
const PROFILE_TYPE_BUSINESS = 'BUSINESS';

const CURRENCY_BTC = 'BTC';
const CURRENCY_ETH = 'ETH';
const CURRENCY_USD = 'USD';
const CURRENCY_EUR = 'EUR';

const KYC_INITIAL = 'INITIAL';
const KYC_INCOMING = 'INCOMING';
const KYC_IN_PROGRESS = 'IN_PROGRESS';
const KYC_APPROVED = 'APPROVED';
const KYC_DENIED = 'DENIED';

const AML_INITIAL = 'INITIAL';
const AML_INCOMING = 'INCOMING';
const AML_APPROVED = 'APPROVED';
const AML_DENIED = 'DENIED';

const PAYMENT_WAITING = 'WAITING';
const PAYMENT_IN_PROGRESS = 'IN_PROGRESS';
const PAYMENT_RECEIVED = 'RECEIVED';

const ETH_BALANCE_IN_WAITING = 'WAITING';
const ETH_BALANCE_IN_CHECKED = 'CHECKED';

const FLOW_STATUS_FIAT_KYC_LINK_SENT = 'FIAT_KYC_LINK_SENT';
const FLOW_STATUS_FIAT_AML_LINK_SENT = 'FIAT_AML_LINK_SENT';
const FLOW_STATUS_FIAT_REVIEW_WAITING = 'FIAT_REVIEW_WAITING';// waiting for aml or kyc rewiew
const FLOW_STATUS_FIAT_PAYMENT_WAITING = 'FIAT_PAYMENT_WAITING';// email with founding page was sent
const FLOW_STATUS_FIAT_REQUEST_KROWNS_SENT = 'FIAT_REQUEST_KROWNS_SENT';// request for krowns to smart contract was sent

const FLOW_STATUS_BTC_MORE_KYC_LINK_SENT = 'BTC_MORE_KYC_LINK_SENT';
const FLOW_STATUS_BTC_MORE_AML_LINK_SENT = 'BTC_MORE_AML_LINK_SENT';
const FLOW_STATUS_BTC_MORE_REVIEW_WAITING = 'BTC_MORE_REVIEW_WAITING';
const FLOW_STATUS_BTC_MORE_PAYMENT_WAITING = 'BTC_MORE_PAYMENT_WAITING';
const FLOW_STATUS_BTC_MORE_REQUEST_KROWNS_SENT = 'BTC_MORE_REQUEST_KROWNS_SENT';

const FLOW_STATUS_BTC_LESS_AML_LINK_SENT = 'BTC_LESS_AML_LINK_SENT';
const FLOW_STATUS_BTC_LESS_PAYMENT_WAITING = 'BTC_LESS_PAYMENT_WAITING';
const FLOW_STATUS_BTC_LESS_REVIEW_DENIED = 'BTC_LESS_REVIEW_DENIED';
const FLOW_STATUS_BTC_LESS_REQUEST_KROWNS_SENT = 'BTC_LESS_REQUEST_KROWNS_SENT';

const FLOW_STATUS_ETH_MORE_KYC_LINK_SENT = 'ETH_MORE_KYC_LINK_SENT';
const FLOW_STATUS_ETH_MORE_AML_LINK_SENT = 'ETH_MORE_AML_LINK_SENT';
const FLOW_STATUS_ETH_MORE_REVIEW_WAITING = 'ETH_MORE_REVIEW_WAITING';
const FLOW_STATUS_ETH_MORE_ETH_ADDR_CONTRACT = 'ETH_MORE_ETH_ADDR_CONTRACT';

const FLOW_STATUS_ETH_LESS_AML_LINK_SENT = 'ETH_LESS_AML_LINK_SENT';
const FLOW_STATUS_ETH_LESS_REVIEW_DENIED = 'ETH_LESS_REVIEW_DENIED';
const FLOW_STATUS_ETH_LESS_ETH_ADDR_CONTRACT = 'ETH_LESS_ETH_ADDR_CONTRACT';

module.exports = {
  USER_ROLES: {
    ADMIN: USER_ROLE_ADMIN,
    USER: USER_ROLE_USER,
  },
  PROFILE_TYPE: {
    PRIVATE: PROFILE_TYPE_PRIVATE,
    BUSINESS: PROFILE_TYPE_BUSINESS,
  },
  CURRENCY: {
    BTC: CURRENCY_BTC,
    ETH: CURRENCY_ETH,
    USD: CURRENCY_USD,
    EUR: CURRENCY_EUR,
  },
  KYC_STATUS: {
    INITIAL: KYC_INITIAL,
    INCOMING: KYC_INCOMING,
    IN_PROGRESS: KYC_IN_PROGRESS,
    APPROVED: KYC_APPROVED,
    DENIED: KYC_DENIED,
  },
  AML_STATUS: {
    INITIAL: AML_INITIAL,
    INCOMING: AML_INCOMING,
    APPROVED: AML_APPROVED,
    DENIED: AML_DENIED,
  },
  PAYMENT_STATUS: {
    WAITING: PAYMENT_WAITING,
    IN_PROGRESS: PAYMENT_IN_PROGRESS,
    RECEIVED: PAYMENT_RECEIVED,
  },
  ETH_BALANCE_IN_STATUS: {
    WAITING: ETH_BALANCE_IN_WAITING,
    CHECKED: ETH_BALANCE_IN_CHECKED,
  },
  FLOW_STATUS: {
    FIAT: {
      KYC_LINK_SENT: FLOW_STATUS_FIAT_KYC_LINK_SENT,
      AML_LINK_SENT: FLOW_STATUS_FIAT_AML_LINK_SENT,
      REVIEW_WAITING: FLOW_STATUS_FIAT_REVIEW_WAITING,
      PAYMENT_WAITING: FLOW_STATUS_FIAT_PAYMENT_WAITING,
      REQUEST_KROWNS_SENT: FLOW_STATUS_FIAT_REQUEST_KROWNS_SENT,
    },
    BTC: {
      MORE: {
        KYC_LINK_SENT: FLOW_STATUS_BTC_MORE_KYC_LINK_SENT,
        AML_LINK_SENT: FLOW_STATUS_BTC_MORE_AML_LINK_SENT,
        REVIEW_WAITING: FLOW_STATUS_BTC_MORE_REVIEW_WAITING,
        PAYMENT_WAITING: FLOW_STATUS_BTC_MORE_PAYMENT_WAITING,
        REQUEST_KROWNS_SENT: FLOW_STATUS_BTC_MORE_REQUEST_KROWNS_SENT,
      },
      LESS: {
        AML_LINK_SENT: FLOW_STATUS_BTC_LESS_AML_LINK_SENT,
        PAYMENT_WAITING: FLOW_STATUS_BTC_LESS_PAYMENT_WAITING,
        REVIEW_DENIED: FLOW_STATUS_BTC_LESS_REVIEW_DENIED,
        REQUEST_KROWNS_SENT: FLOW_STATUS_BTC_LESS_REQUEST_KROWNS_SENT,
      },
    },
    ETH: {
      MORE: {
        KYC_LINK_SENT: FLOW_STATUS_ETH_MORE_KYC_LINK_SENT,
        AML_LINK_SENT: FLOW_STATUS_ETH_MORE_AML_LINK_SENT,
        REVIEW_WAITING: FLOW_STATUS_ETH_MORE_REVIEW_WAITING,
        ETH_ADDR_CONTRACT: FLOW_STATUS_ETH_MORE_ETH_ADDR_CONTRACT,
      },
      LESS: {
        AML_LINK_SENT: FLOW_STATUS_ETH_LESS_AML_LINK_SENT,
        REVIEW_DENIED: FLOW_STATUS_ETH_LESS_REVIEW_DENIED,
        ETH_ADDR_CONTRACT: FLOW_STATUS_ETH_LESS_ETH_ADDR_CONTRACT,
      },
    },
  },
};
